In [1]:
import pandas as pd
import sasoptpy as so
import requests
import os
import time

In [42]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
# Data
r = requests.get('https://fantasy.premierleague.com/api/bootstrap-static/')
fpl_data = r.json()

In [3]:
element_data = pd.DataFrame(fpl_data['elements'])

In [4]:
element_data.head()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,0.0,75.0,438098,-1,1,-1,1,0,3,0.0,...,170,107,601,271,601,271,567,246,0.0,0.0
1,75.0,NaN,205651,-1,1,-2,2,0,4,0.8,...,37,17,625,68,625,68,175,30,0.0,0.0
2,NaN,NaN,226597,0,0,0,0,0,2,7.0,...,81,5,31,8,35,10,28,10,1.0,1.0
3,NaN,NaN,219847,0,0,1,-1,1,4,8.0,...,12,4,17,3,18,3,18,5,1.0,1.0
4,0.0,0.0,463748,0,0,0,0,0,1,0.0,...,608,63,380,45,380,45,507,63,0.0,0.0

In [5]:
team_data = pd.DataFrame(fpl_data['teams'])
team_data.head()

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,...,None,False,0,1350,1380,1370,1370,1330,1390,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,...,None,False,0,1120,1245,1110,1140,1130,1350,2
2,91,0,None,3,0,Bournemouth,0,0,0,BOU,...,None,False,0,1100,1100,1075,1100,1130,1105,127
3,94,0,None,4,0,Brentford,0,0,0,BRE,...,None,False,0,1100,1100,1105,1095,1100,1110,130
4,36,0,None,5,0,Brighton,0,0,0,BHA,...,None,False,0,1100,1100,1100,1105,1100,1100,131

In [6]:
elements_team = pd.merge(element_data, team_data, left_on='team', right_on='id')

In [7]:
with pd.option_context('display.max_rows', None):
    print(elements_team.loc[0])

chance_of_playing_next_round                                                          0.0
chance_of_playing_this_round                                                         75.0
code_x                                                                             438098
cost_change_event                                                                      -1
cost_change_event_fall                                                                  1
cost_change_start                                                                      -1
cost_change_start_fall                                                                  1
dreamteam_count                                                                         0
element_type                                                                            3
ep_next                                                                               0.0
ep_this                                                                               0.8
event_points                                                                            0
first_name                                                                          FÃ¡bio
form_x                                                                                0.0
id_x                                                                                    1
in_dreamteam                                                                        False
news                                    Has joined Portuguese side FC Porto on loan fo...
news_added                                                    2024-08-29T11:06:25.241953Z
now_cost                                                                               54
photo                                                                          438098.jpg
points_per_game                                                                       0.0
second_name                                                               Ferreira Vieira
selected_by_percent                                                                   0.0
special                                                                             False
squad_number                                                                         None
status                                                                                  u
team                                                                                    1
team_code                                                                               3
total_points                                                                            0
transfers_in                                                                          439
transfers_in_event                                                                    355
transfers_out                                                                        1296
transfers_out_event                                                                   422
value_form                                                                            0.0
value_season                                                                          0.0
web_name                                                                     FÃ¡bio Vieira
minutes                                                                                 0
goals_scored                                                                            0
assists                                                                                 0
clean_sheets                                                                            0
goals_conceded                                                                          0
own_goals                                                                               0
penalties_saved                                                                         0
penalties_missed                                                                        0
yellow_cards                                                                            0
red_cards                                                                               0
saves                                                                                   0
bonus                                                                                   0
bps                                                                                     0
influence                                                                             0.0
creativity                                                                            0.0
threat                                                                                0.0
ict_index                                                                             0.0
starts                                                                                  0
expected_goals                                                                       0.00
expected_assists                                                                     0.00
expected_goal_involvements                                                           0.00
expected_goals_conceded                                                              0.00
influence_rank                                                                        600
influence_rank_type                                                                   267
creativity_rank                                                                       602
creativity_rank_type                                                                  272
threat_rank                                                                           591
threat_rank_type                                                                      266
ict_index_rank                                                                        605
ict_index_rank_type                                                                   272
corners_and_indirect_freekicks_order                                                  NaN
corners_and_indirect_freekicks_text
direct_freekicks_order                                                                NaN
direct_freekicks_text
penalties_order                                                                       4.0
penalties_text
expected_goals_per_90                                                                 0.0
saves_per_90                                                                          0.0
expected_assists_per_90                                                               0.0
expected_goal_involvements_per_90                                                     0.0
expected_goals_conceded_per_90                                                        0.0
goals_conceded_per_90                                                                 0.0
now_cost_rank                                                                         170
now_cost_rank_type                                                                    107
form_rank                                                                             601
form_rank_type                                                                        271
points_per_game_rank                                                                  601
points_per_game_rank_type                                                             271
selected_rank                                                                         567
selected_rank_type                                                                    246
starts_per_90                                                                         0.0
clean_sheets_per_90                                                                   0.0
code_y                                                                                  3
draw                                                                                    0
form_y                                                                               None
id_y                                                                                    1
loss                                                                                    0
name                                                                              Arsenal
played                                                                                  0
points                                                                                  0
position                                                                                0
short_name                                                                            ARS
strength                                                                                5
team_division                                                                        None
unavailable                                                                         False
win                                                                                     0
strength_overall_home                                                                1350
strength_overall_away                                                                1380
strength_attack_home                                                                 1370
strength_attack_away                                                                 1370
strength_defence_home                                                                1330
strength_defence_away                                                                1390
pulse_id                                                                                1
Name: 0, dtype: object

In [8]:
review_data = pd.read_csv('../data/fplreview.csv')

In [9]:
review_data.head()

,Pos,ID,Name,BV,SV,Team,3_xMins,3_Pts,4_xMins,4_Pts,...,6_Pts,7_xMins,7_Pts,8_xMins,8_Pts,9_xMins,9_Pts,10_xMins,10_Pts,Elite%
0,M,1,FÃ¡bio Vieira,5.4,5.4,Arsenal,0,0.00,4,0.23,...,0.67,9,0.70,10,0.61,9,0.56,11,0.63,0.00
1,F,2,G.Jesus,6.8,6.8,Arsenal,1,0.10,30,1.84,...,2.85,35,2.94,35,2.29,35,2.15,37,2.30,0.00
2,D,3,Gabriel,6.0,6.0,Arsenal,88,4.26,86,3.19,...,4.75,81,4.74,80,3.64,78,3.06,77,3.08,0.45
3,F,4,Havertz,8.1,8.1,Arsenal,90,5.50,84,4.23,...,5.62,79,5.85,79,4.23,78,4.14,78,4.14,0.01
4,G,5,Hein,4.0,4.0,Arsenal,0,0.00,0,0.00,...,0.00,0,0.00,0,0.00,0,0.00,0,0.00,0.00

In [10]:
merged_data = pd.merge(elements_team, review_data, left_on=['name', 'web_name'], right_on=['Team', 'Name'])

In [11]:
with pd.option_context('display.max_rows', None):
    print(merged_data[merged_data['web_name'] == 'Saka'].iloc[0])

chance_of_playing_next_round                   NaN
chance_of_playing_this_round                   NaN
code_x                                      223340
cost_change_event                                0
cost_change_event_fall                           0
cost_change_start                                0
cost_change_start_fall                           0
dreamteam_count                                  1
element_type                                     3
ep_next                                       10.0
ep_this                                       10.0
event_points                                     6
first_name                                  Bukayo
form_x                                         9.0
id_x                                            17
in_dreamteam                                  True
news
news_added                                    None
now_cost                                       100
photo                                   223340.jpg
points_per_game                                9.0
second_name                                   Saka
selected_by_percent                           34.2
special                                      False
squad_number                                  None
status                                           a
team                                             1
team_code                                        3
total_points                                    18
transfers_in                                501100
transfers_in_event                          260812
transfers_out                               289873
transfers_out_event                         191527
value_form                                     0.9
value_season                                   1.8
web_name                                      Saka
minutes                                        166
goals_scored                                     1
assists                                          2
clean_sheets                                     2
goals_conceded                                   0
own_goals                                        0
penalties_saved                                  0
penalties_missed                                 0
yellow_cards                                     1
red_cards                                        0
saves                                            0
bonus                                            2
bps                                             63
influence                                     92.0
creativity                                    89.1
threat                                       105.0
ict_index                                     28.6
starts                                           2
expected_goals                                0.40
expected_assists                              0.47
expected_goal_involvements                    0.87
expected_goals_conceded                       1.57
influence_rank                                   7
influence_rank_type                              4
creativity_rank                                  7
creativity_rank_type                             6
threat_rank                                      3
threat_rank_type                                 2
ict_index_rank                                   1
ict_index_rank_type                              1
corners_and_indirect_freekicks_order           1.0
corners_and_indirect_freekicks_text
direct_freekicks_order                         NaN
direct_freekicks_text
penalties_order                                1.0
penalties_text
expected_goals_per_90                         0.22
saves_per_90                                   0.0
expected_assists_per_90                       0.25
expected_goal_involvements_per_90             0.47
expected_goals_conceded_per_90                0.85
goals_conceded_per_90                          0.0
now_cost_rank                                    5
now_cost_rank_type                               4
form_rank                                        8
form_rank_type                                   5
points_per_game_rank                             9
points_per_game_rank_type                        6
selected_rank                                    7
selected_rank_type                               3
starts_per_90                                 1.08
clean_sheets_per_90                           1.08
code_y                                           3
draw                                             0
form_y                                        None
id_y                                             1
loss                                             0
name                                       Arsenal
played                                           0
points                                           0
position                                         0
short_name                                     ARS
strength                                         5
team_division                                 None
unavailable                                  False
win                                              0
strength_overall_home                         1350
strength_overall_away                         1380
strength_attack_home                          1370
strength_attack_away                          1370
strength_defence_home                         1330
strength_defence_away                         1390
pulse_id                                         1
Pos                                              M
ID                                              17
Name                                          Saka
BV                                            10.0
SV                                            10.0
Team                                       Arsenal
3_xMins                                         87
3_Pts                                         6.79
4_xMins                                         86
4_Pts                                          5.3
5_xMins                                         84
5_Pts                                         4.04
6_xMins                                         80
6_Pts                                         7.45
7_xMins                                         78
7_Pts                                         7.45
8_xMins                                         80
8_Pts                                         5.41
9_xMins                                         80
9_Pts                                         5.32
10_xMins                                        80
10_Pts                                        5.35
Elite%                                         0.9
Name: 15, dtype: object

In [12]:
merged_data.set_index(['id_x'], inplace=True)

In [13]:
next_gw = int(review_data.keys()[6].split('_')[0])

In [14]:
next_gw

3

In [15]:
type_data = pd.DataFrame(fpl_data['element_types']).set_index(['id'])

In [16]:
type_data.head()

,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_select,squad_max_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
id,,,,,,,,,,,,
1,Goalkeepers,GKP,Goalkeeper,GKP,2,None,None,1,1,True,[12],67
2,Defenders,DEF,Defender,DEF,5,None,None,3,5,False,[],207
3,Midfielders,MID,Midfielder,MID,5,None,None,2,5,False,[],287
4,Forwards,FWD,Forward,FWD,3,None,None,1,3,False,[],72

In [17]:
model = so.Model(name='single_period')

NOTE: Initialized model single_period.

In [18]:
players = merged_data.index.tolist()

In [19]:
element_types = type_data.index.tolist()

In [20]:
teams = team_data['name'].tolist()

In [21]:
squad = model.add_variables(players, name='squad', vartype=so.binary)
lineup = model.add_variables(players, name='lineup', vartype=so.binary)
captain = model.add_variables(players, name='captain', vartype=so.binary)
vicecap = model.add_variables(players, name='vicecap', vartype=so.binary)

In [22]:
squad_count = so.expr_sum(squad[p] for p in players)

In [23]:
model.add_constraint(squad_count == 15, name='squad_count');

In [24]:
model.add_constraint(so.expr_sum(lineup[p] for p in players) == 11, name='lineup_count');

In [25]:
model.add_constraint(so.expr_sum(captain[p] for p in players) == 1, name='captain_count');
model.add_constraint(so.expr_sum(vicecap[p] for p in players) == 1, name='vicecap_count');

In [26]:
# lineup has to have less players than squad
model.add_constraints((lineup[p] <= squad[p] for p in players), name='lineup_squad_rel'); 

# captain has to be in lineup
model.add_constraints((captain[p] <= lineup[p] for p in players), name='captain_lineup_rel'); 

# vice captain has to be in lineup
model.add_constraints((vicecap[p] <= lineup[p] for p in players), name='vicecap_lineup_rel'); 

# captain and vice captain cannot be the same player
model.add_constraints((captain[p] + vicecap[p] <= 1 for p in players), name='captain_vicecap_rel');

In [27]:
lineup_type_count = {t: so.expr_sum(lineup[p] for p in players if merged_data.loc[p, 'element_type'] == t)
                     for t in element_types}

In [28]:
squad_type_count = {t: so.expr_sum(squad[p] for p in players if merged_data.loc[p, 'element_type'] == t)
                     for t in element_types}

In [29]:
model.add_constraints((lineup_type_count[t] == [type_data.loc[t, 'squad_min_play'], type_data.loc[t, 'squad_max_play']]
                       for t in element_types), name='valid_formation');

In [30]:
model.add_constraints((squad_type_count[t] == type_data.loc[t, 'squad_select'] for t in element_types),
                      name='valid_squad');

In [31]:
budget = 100
price = so.expr_sum(merged_data.loc[p, 'now_cost'] / 10 * squad[p] for p in players)

In [32]:
model.add_constraint(price <= budget, name='satisfies_budget');

In [33]:
model.add_constraints((so.expr_sum(squad[p] for p in players if merged_data.loc[p, 'name'] == t) <= 3 for t in teams), 
                     name='team_limit');

In [34]:
total_points = so.expr_sum(merged_data.loc[p, f'{next_gw}_Pts'] * (lineup[p] + captain[p] + 0.1*vicecap[p])
                           for p in players)

In [35]:
model.set_objective(-total_points, sense='N', name='total_xp'); # -total_points because it is minimizing the minimizer

In [44]:
model.export_mps(filename='single_period.mps')

In [45]:
command = 'cbc single_period.mps solve solu sp_solution.txt'

In [47]:
!{command}

Welcome to the CBC MILP Solver
Version: 2.10.12
Build Date: Aug 20 2024

command line - cbc single_period.mps solve solu sp_solution.txt (default strategy 1)
At line 1 NAME    single_period
At line 2 ROWS
At line 2529 COLUMNS
At line 8760 RHS
At line 9089 RANGES
At line 9093 BOUNDS
At line 11586 ENDATA
Problem single_period has 2525 rows, 2492 columns and 9968 elements
Coin0008I single_period read with 0 errors
Continuous objective value is -65.7031 - 0.01 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1869 strengthened rows, 0 substitutions
Cgl0004I processed model has 1550 rows, 2492 columns (2492 integer (2492 of which binary)) and 8912 elements
Cutoff increment increased from 1e-05 to 0.000999
Cbc0038I Initial state - 12 integers unsatisfied sum - 2.68421
Cbc0038I Pass   1: suminf.    0.96226 (6) obj. -64.9995 iterations 207
Cbc0038I Solution found of -58.798
Cbc0038I Before mini branch and bound, 2477 integers at bound fixed and 0 continuous
Cbc0038I Full problem 1550 rows 2492 columns, reduced to 7 rows 7 columns
Cbc0038I Mini branch and bound improved solution from -58.798 to -64.009 (0.06 seconds)
Cbc0038I Round again with cutoff of -64.1787
Cbc0038I Reduced cost fixing fixed 1076 variables on major pass 2
Cbc0038I Pass   2: suminf.    0.96226 (6) obj. -65.3234 iterations 23
Cbc0038I Pass   3: suminf.    1.32211 (4) obj. -64.1787 iterations 196
Cbc0038I Pass   4: suminf.    0.64151 (4) obj. -65.0329 iterations 118
Cbc0038I Pass   5: suminf.    1.21309 (8) obj. -64.1787 iterations 367
Cbc0038I Pass   6: suminf.    0.77571 (6) obj. -64.1787 iterations 44
Cbc0038I Pass   7: suminf.    1.81677 (4) obj. -64.1787 iterations 63
Cbc0038I Pass   8: suminf.    0.70833 (4) obj. -65.1332 iterations 201
Cbc0038I Pass   9: suminf.    1.66759 (4) obj. -64.1787 iterations 149
Cbc0038I Pass  10: suminf.    2.46424 (6) obj. -64.1787 iterations 91
Cbc0038I Pass  11: suminf.    0.64151 (4) obj. -65.0955 iterations 187
Cbc0038I Pass  12: suminf.    1.43348 (4) obj. -64.1787 iterations 130
Cbc0038I Pass  13: suminf.    1.76268 (12) obj. -64.1787 iterations 45
Cbc0038I Pass  14: suminf.    0.75000 (6) obj. -64.4005 iterations 169
Cbc0038I Pass  15: suminf.    0.72287 (4) obj. -64.1787 iterations 190
Cbc0038I Pass  16: suminf.    0.50000 (4) obj. -64.4005 iterations 118
Cbc0038I Pass  17: suminf.    1.45073 (8) obj. -64.1787 iterations 232
Cbc0038I Pass  18: suminf.    0.50000 (4) obj. -64.2385 iterations 232
Cbc0038I Pass  19: suminf.    0.56005 (4) obj. -64.1787 iterations 93
Cbc0038I Pass  20: suminf.    1.28095 (8) obj. -64.1787 iterations 281
Cbc0038I Pass  21: suminf.    0.60387 (4) obj. -64.1787 iterations 48
Cbc0038I Pass  22: suminf.    0.43750 (6) obj. -64.9586 iterations 172
Cbc0038I Pass  23: suminf.    0.75302 (4) obj. -64.1787 iterations 152
Cbc0038I Pass  24: suminf.    0.29167 (4) obj. -64.6378 iterations 156
Cbc0038I Pass  25: suminf.    2.10995 (8) obj. -64.1787 iterations 438
Cbc0038I Pass  26: suminf.    0.29167 (4) obj. -64.6378 iterations 267
Cbc0038I Pass  27: suminf.    0.75302 (4) obj. -64.1787 iterations 112
Cbc0038I Pass  28: suminf.    1.85493 (4) obj. -64.1787 iterations 712
Cbc0038I Pass  29: suminf.    1.85493 (4) obj. -64.1787 iterations 222
Cbc0038I Pass  30: suminf.    0.70833 (4) obj. -65.1042 iterations 150
Cbc0038I Pass  31: suminf.    1.63844 (4) obj. -64.1787 iterations 74
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 2425 integers at bound fixed and 0 continuous
Cbc0038I Full problem 1550 rows 2492 columns, reduced to 44 rows 60 columns
Cbc0038I Mini branch and bound improved solution from -64.009 to -65.309 (0.15 seconds)
Cbc0038I Round again with cutoff of -65.3875
Cbc0038I Reduced cost fixing fixed 1874 variables on major pass 3
Cbc0038I Pass  31: suminf.    1.06250 (6) obj. -65.6099 iterations 54
Cbc0038I Pass  32: suminf.    0.78224 (4) obj. -65.3875 iterations 173
Cbc0038I Pass  33: suminf.    0.70833 (4) obj. -65.4437 iterations 43
Cbc0038I Pass  34: suminf.    1.85673 (8) obj. -65.3875 iterations 36
Cbc0038I Pass  35: suminf.    0.70833 (4) obj. -65.5427 iterations 13
Cbc0038I Pass  36: suminf.    0.91250 (4) obj. -65.3875 iterations 29
Cbc0038I Pass  37: suminf.    2.18167 (12) obj. -65.3875 iterations 33
Cbc0038I Pass  38: suminf.    1.82529 (12) obj. -65.3875 iterations 11
Cbc0038I Pass  39: suminf.    2.82812 (8) obj. -65.3875 iterations 39
Cbc0038I Pass  40: suminf.    2.75962 (8) obj. -65.3875 iterations 8
Cbc0038I Pass  41: suminf.    3.10252 (10) obj. -65.3875 iterations 31
Cbc0038I Pass  42: suminf.    1.55098 (8) obj. -65.3875 iterations 35
Cbc0038I Pass  43: suminf.    1.37717 (6) obj. -65.3875 iterations 50
Cbc0038I Pass  44: suminf.    0.70833 (4) obj. -65.5427 iterations 15
Cbc0038I Pass  45: suminf.    0.91250 (4) obj. -65.3875 iterations 47
Cbc0038I Pass  46: suminf.    4.36470 (10) obj. -65.3875 iterations 26
Cbc0038I Pass  47: suminf.    1.37500 (6) obj. -65.441 iterations 48
Cbc0038I Pass  48: suminf.    1.90515 (6) obj. -65.3875 iterations 30
Cbc0038I Pass  49: suminf.    1.85370 (12) obj. -65.3875 iterations 34
Cbc0038I Pass  50: suminf.    1.06250 (6) obj. -65.4917 iterations 14
Cbc0038I Pass  51: suminf.    0.84540 (4) obj. -65.3875 iterations 35
Cbc0038I Pass  52: suminf.    0.70833 (4) obj. -65.4917 iterations 25
Cbc0038I Pass  53: suminf.    1.48932 (10) obj. -65.3875 iterations 21
Cbc0038I Pass  54: suminf.    0.70833 (4) obj. -65.4917 iterations 13
Cbc0038I Pass  55: suminf.    0.84540 (4) obj. -65.3875 iterations 22
Cbc0038I Pass  56: suminf.    1.53131 (10) obj. -65.3875 iterations 40
Cbc0038I Pass  57: suminf.    0.70833 (4) obj. -65.4917 iterations 17
Cbc0038I Pass  58: suminf.    0.84540 (4) obj. -65.3875 iterations 21
Cbc0038I Pass  59: suminf.    1.86633 (10) obj. -65.3875 iterations 27
Cbc0038I Pass  60: suminf.    3.08886 (8) obj. -65.3875 iterations 46
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 2415 integers at bound fixed and 0 continuous
Cbc0038I Full problem 1550 rows 2492 columns, reduced to 43 rows 65 columns
Cbc0038I Mini branch and bound did not improve solution (0.20 seconds)
Cbc0038I After 0.20 seconds - Feasibility pump exiting with objective of -65.309 - took 0.15 seconds
Cbc0012I Integer solution of -65.309 found by feasibility pump after 0 iterations and 0 nodes (0.20 seconds)
Cbc0038I Full problem 1550 rows 2492 columns, reduced to 14 rows 13 columns
Cbc0013I At root node, 0 cuts changed objective from -65.697487 to -65.697487 in 1 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 35 column cuts (35 active)  in 0.001 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.002 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.001 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.001 seconds - new frequency is -100
Cbc0010I After 0 nodes, 1 on tree, -65.309 best solution, best possible -65.369 (0.23 seconds)
Cbc0001I Search completed - best objective -65.30900000000001, took 62 iterations and 2 nodes (0.24 seconds)
Cbc0032I Strong branching done 12 times (33 iterations), fathomed 2 nodes and fixed 0 variables
Cbc0035I Maximum depth 0, 2631 variables fixed on reduced cost
Cuts at root node changed objective from -65.6975 to -65.369
Probing was tried 3 times and created 37 cuts of which 0 were active after adding rounds of cuts (0.002 seconds)
Gomory was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.002 seconds)
Knapsack was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)
Clique was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)
TwoMirCuts was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.001 seconds)

Result - Optimal solution found

Objective value:                -65.30900000
Enumerated nodes:               2
Total iterations:               62
Time (CPU seconds):             0.24
Time (Wallclock seconds):       0.27

Total time (CPU seconds):       0.25   (Wallclock seconds):       0.28

In [49]:
for v in model.get_variables():
    v.set_value(0)

In [51]:
with open('sp_solution.txt', 'r') as f:
    for line in f:
        if 'objective value' in line:
            continue
        words = line.split()
        var = model.get_variable(words[1])
        var.set_value(float(words[2]))

In [63]:
picks = []
for p in players:
    if squad[p].get_value() > 0.5:
        lp = merged_data.loc[p]
        is_lineup = 1 if lineup[p].get_value() > 0.5 else 0
        is_captain = 1 if captain[p].get_value() > 0.5 else 0
        is_vicecap = 1 if vicecap[p].get_value() > 0.5 else 0
        position = type_data.loc[lp['element_type'], 'singular_name_short']
        picks.append([
            lp['web_name'], position, lp['element_type'], lp['name'], lp['now_cost']/10,
            round(lp[f'{next_gw}_Pts'], 2), is_lineup, is_captain, is_vicecap
        ])
        
picks_df = pd.DataFrame(picks, columns = ['name', 'position', 'type', 'team', 'price', 'xP', 'lineup',
                                          'captain', 'vice captain'])

In [64]:
picks_df

,name,position,type,team,price,xP,lineup,captain,vice captain
0,Gabriel,DEF,2,Arsenal,6.0,4.26,1,0,0
1,Havertz,FWD,4,Arsenal,8.1,5.50,1,0,0
2,Saka,MID,3,Arsenal,10.0,6.79,1,0,1
3,Konsa,DEF,2,Aston Villa,4.5,3.58,1,0,0
4,Flekken,GKP,1,Brentford,4.5,3.74,1,0,0
5,Mbeumo,MID,3,Brentford,7.0,6.01,1,0,0
6,Gusto,DEF,2,Chelsea,5.0,3.70,1,0,0
7,Palmer,MID,3,Chelsea,10.5,7.04,1,1,0
8,Wiley,DEF,2,Chelsea,4.0,0.00,0,0,0
9,M.Salah,MID,3,Liverpool,12.6,6.07,1,0,0
10,Isak,FWD,4,Newcastle,8.5,5.88,1,0,0
11,Gibbs-White,MID,3,Nott'm Forest,6.5,5.02,1,0,0
12,Bednarek,DEF,2,Southampton,4.0,2.02,0,0,0
13,Lankshear,FWD,4,Spurs,4.5,0.00,0,0,0
14,Bentley,GKP,1,Wolves,4.0,0.00,0,0,0

In [68]:
picks_df['xP'].sum()

np.float64(59.61000000000001)